"""Updated page and section models

Revision ID: ae666acb7bd8
Revises: 921b0adda9f6
Create Date: 2024-07-29 14:15:47.892042

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae666acb7bd8'
down_revision: Union[str, None] = '921b0adda9f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('page', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('page', sa.Column('beta', sa.Boolean(), nullable=False))
    op.add_column('page', sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('page', 'path')
    op.drop_column('page', 'beta')
    op.drop_column('page', 'active')
    # ### end Alembic commands ###
